apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: rvay4p7hn-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-14864718c9.f59b.p3.openshiftapps.com/rhtap/rhtap-qe:9b47f3564f3c2cc25c03ce52f11d6c798b4b96da@sha256:6370de2c910ffb2ec3f4a6435b61a98d6a77bb51520b6197477087fc08306e7e
          name: container-image
