apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: rvay4p7hn-go
  janus-idp.io/tekton: rvay4p7hn-go
  backstage.io/kubernetes-id: rvay4p7hn-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rvay4p7hn-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
