apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: rvay4p7hn-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rvay4p7hn-go 
  name: rvay4p7hn-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: rvay4p7hn-go 
